services:

  vpn_server_alma_8:
    image: alma8:v1
    build: vpn_alma_8/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_alma_9:
    image: alma9:v1
    build: vpn_alma_9/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_rocky_8:
    image: rocky8:v1
    build: vpn_rocky_8/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_rocky_9:
    image: rocky9:v1
    build: vpn_rocky_9/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22


  ansible:
    build: ansible/
    image: ans_pyth3_9_20:v1
    volumes:
      - ssh_pub_key:/ans_user_home/key/
      - ./ansible/roles:/ans_user_home/roles
    ports:
      -  22
    env_file: ./ansible/ans.env
    depends_on:
      - vpn_server_alma_8
      - vpn_server_alma_9
      - vpn_server_rocky_8
      - vpn_server_rocky_9


volumes:
  ssh_pub_key:
