version: "3"

services:

  vpn_server:
    build: vpn/
    volumes:
      - ssh_pub_key:/app/.ssh/
    ports:
      -  22

  ansible:
    build: ansible/
    volumes:
      - ssh_pub_key:/ans_user_home/key/
    ports:
      -  22
    env_file: ans.env
    depends_on:
      - vpn_server


volumes:
  ssh_pub_key:

