services:

  vpn_server_alma_8:
    image: a8_new
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_alma_9:
    image: a9_new
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_rocky_8:
    image: r8_new
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_rocky_9:
    image: r9_new
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22


  ansible:
    image: ans_new
    volumes:
      - ssh_pub_key:/ans_user_home/key/
      - ./ansible/roles:/ans_user_home/roles
    ports:
      -  22
    env_file: ./ansible/ans.env
    depends_on:
      - vpn_server_alma_8
      - vpn_server_alma_9
      - vpn_server_rocky_8
      - vpn_server_rocky_9


volumes:
  ssh_pub_key:
