services:

  vpn_server_alma_8:
    image: almalinux:8-minimal
    build: vpn_alma_8/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_alma_9:
    image: almalinux:9-minimal
    build: vpn_alma_9/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_rocky_8:
    image: rockylinux:8-minimal
    build: vpn_rocky_8/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22

  vpn_server_rocky_9:
    image: rockylinux:9-minimal
    build: vpn_rocky_9/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22


  ansible:
    build: ansible/
    image: python:3.9.20-alpine3.20
    volumes:
      - ssh_pub_key:/ans_user_home/key/
      - ./ansible/roles:/ans_user_home/roles
    ports:
      -  22
    env_file: ./ansible/ans.env
    depends_on:
      - vpn_server_alma_8
      - vpn_server_alma_9
      - vpn_server_rocky_8
      - vpn_server_rocky_9


volumes:
  ssh_pub_key:
