services:

  vpn_server_ubuntu:
    image: ubuntu_vpn
    build: ubuntu/
    volumes:
      - ssh_pub_key:/home/vpn_user/.ssh/
    ports:
      -  22


  ansible:
    build: ansible/
    image: ans_pyth3_9_20
    volumes:
      - ssh_pub_key:/ans_user_home/key/
      - ./ansible/roles:/ans_user_home/roles
    ports:
      -  22
    env_file: ./ansible/ans.env
    depends_on:
      - vpn_server_ubuntu


volumes:
  ssh_pub_key:
